<a href="https://colab.research.google.com/github/Desmondonam/data_bank/blob/main/sales_data.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd

In [2]:

file_path1 = '/content/Sales_January_2019.csv'
file_path2 = '/content/Sales_February_2019.csv'
file_path3 = '/content/Sales_March_2019.csv'
file_path4 = '/content/Sales_April_2019.csv'
file_path5 = '/content/Sales_May_2019.csv'
file_path6 = '/content/Sales_June_2019.csv'
file_path7 = '/content/Sales_July_2019.csv'
file_path8 = '/content/Sales_August_2019.csv'
file_path9 = '/content/Sales_September_2019.csv'
file_path10 = '/content/Sales_October_2019.csv'
file_path11 = '/content/Sales_November_2019.csv'
file_path12 = '/content/Sales_December_2019.csv'

In [3]:
## Load the data into seperate dataframes
df_month1 = pd.read_csv(file_path1)
df_month2 = pd.read_csv(file_path2)
df_month3 = pd.read_csv(file_path3)
df_month4 = pd.read_csv(file_path4)
df_month5 = pd.read_csv(file_path5)
df_month6 = pd.read_csv(file_path6)
df_month7 = pd.read_csv(file_path7)
df_month8 = pd.read_csv(file_path8)
df_month9 = pd.read_csv(file_path9)
df_month10 = pd.read_csv(file_path10)
df_month11 = pd.read_csv(file_path11)
df_month12 = pd.read_csv(file_path12)

In [4]:
combined_df = pd.concat([df_month1, df_month2, df_month3,df_month4, df_month5, df_month6, df_month7 ,df_month8, df_month9, df_month10, df_month11, df_month12], ignore_index=True)

In [5]:
combined_df.head()

,Order ID,Product,Quantity Ordered,Price Each,Order Date,Purchase Address
0,141234,iPhone,1,700,01/22/19 21:25,"944 Walnut St, Boston, MA 02215"
1,141235,Lightning Charging Cable,1,14.95,01/28/19 14:15,"185 Maple St, Portland, OR 97035"
2,141236,Wired Headphones,2,11.99,01/17/19 13:33,"538 Adams St, San Francisco, CA 94016"
3,141237,27in FHD Monitor,1,149.99,01/05/19 20:33,"738 10th St, Los Angeles, CA 90001"
4,141238,Wired Headphones,1,11.99,01/25/19 11:59,"387 10th St, Austin, TX 73301"

In [6]:
combined_df.tail()

,Order ID,Product,Quantity Ordered,Price Each,Order Date,Purchase Address
186845,319666,Lightning Charging Cable,1,14.95,12/11/19 20:58,"14 Madison St, San Francisco, CA 94016"
186846,319667,AA Batteries (4-pack),2,3.84,12/01/19 12:01,"549 Willow St, Los Angeles, CA 90001"
186847,319668,Vareebadd Phone,1,400,12/09/19 06:43,"273 Wilson St, Seattle, WA 98101"
186848,319669,Wired Headphones,1,11.99,12/03/19 10:39,"778 River St, Dallas, TX 75001"
186849,319670,Bose SoundSport Headphones,1,99.99,12/21/19 21:45,"747 Chestnut St, Los Angeles, CA 90001"

In [7]:
combined_df.to_csv('combined_sales_data.csv', index=False)